# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c88e6d578064e7b1e64191ef310949752a8b82bddca4e79e608b5788e8618d57ce0d64b539298d009f7ce39192d46695e64cdab4743d4fbfc6d47f2abeae06d

test:
  secret_key_base: 00a977562bbfe98d6f46624ea2829af0361177a75968655460ed25dc66a3ad7f7ea3ac8ee81d1d8fec0e8b685a1c3933e0b6d9f6dc80b1215b0f9ab87985ac8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
